import swaggerUi from 'swagger-ui-express';
import yaml from 'yamljs';
import path from 'path';

// Завантажуємо файл
const swaggerDocument = yaml.load(path.resolve('./swagger.yaml'));

// Налаштовуємо ендпоінт
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
